spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: Dt21424818
    driver-class-name: com.mysql.cj.jdbc.Driver
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

      spring.jpa.properties.hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        enable_lazy_load_no_trans: true

